FROM ghcr.io/gitleaks/gitleaks:v8.28.0 AS gitleaks
FROM ghcr.io/anchore/syft:v1.52.0 AS syft
FROM ghcr.io/sigstore/cosign/cosign:v3.1.3 AS cosign
FROM openpolicyagent/opa:1.20.2-static AS opa
FROM aquasec/trivy:0.74.0 AS trivy
FROM registry.k8s.io/kubectl:v1.34.1 AS kubectl
FROM hashicorp/terraform:1.13.4 AS terraform
FROM aquasec/tfsec:v1.28.14 AS tfsec

FROM node:20-alpine

USER root

RUN apk add --no-cache \
    docker-cli \
    docker-cli-compose \
    git \
    jq \
    openjdk17-jre \
    openssh-client \
    py3-pip \
    python3 \
    && python3 -m venv /opt/semgrep \
    && /opt/semgrep/bin/pip install --no-cache-dir semgrep==1.178.0 \
    && python3 -m venv /opt/iac \
    && /opt/iac/bin/pip install --no-cache-dir \
        ansible-lint==26.9.0 \
        checkov==3.3.20

COPY --from=gitleaks /usr/bin/gitleaks /usr/local/bin/gitleaks
COPY --from=syft /syft /usr/local/bin/syft
COPY --from=cosign /ko-app/cosign /usr/local/bin/cosign
COPY --from=opa /opa /usr/local/bin/opa
COPY --from=trivy /usr/local/bin/trivy /usr/local/bin/trivy
COPY --from=kubectl /bin/kubectl /usr/local/bin/kubectl
COPY --from=terraform /bin/terraform /usr/local/bin/terraform
COPY --from=tfsec /usr/bin/tfsec /usr/local/bin/tfsec

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk
ENV PATH="/opt/semgrep/bin:/opt/iac/bin:${JAVA_HOME}/bin:${PATH}"

RUN gitleaks version \
    && semgrep --version \
    && jq --version \
    && syft version \
    && cosign version \
    && opa version \
    && trivy --version \
    && kubectl version --client \
    && terraform version \
    && tfsec --version \
    && checkov --version \
    && ansible --version \
    && ansible-lint --version \
    && docker --version \
    && docker compose version \
    && java -version
